-- Initial Kora schema — Oracle dialect.
--
-- Parallel of migrations/001_initial_schema.sql (PostgreSQL). Oracle-specific
-- translations applied:
--   BIGSERIAL          -> NUMBER(19) GENERATED BY DEFAULT AS IDENTITY
--   BOOLEAN            -> NUMBER(1) CHECK (.. IN (0,1))  (Oracle has no BOOLEAN)
--   TIMESTAMPTZ        -> TIMESTAMP WITH TIME ZONE
--   now()             -> SYSTIMESTAMP
--   TEXT (large)       -> CLOB ;  TEXT (bounded) -> VARCHAR2
--   partial unique idx -> function-based unique index
--   config."mode"      -> registry_mode  (MODE is an Oracle reserved word; the
--                         Postgres schema keeps "mode" — the backends are separate)
--
-- The whole migration is one idempotent PL/SQL block: every DDL is run through
-- a helper that swallows ORA-00955 ("name already used") and ORA-01408 ("column
-- list already indexed"), so re-running on an already-migrated database is a
-- no-op. Requires Oracle 19c+ (128-char identifiers, identity columns).
BEGIN
    DECLARE
        PROCEDURE ddl(p_sql IN VARCHAR2) IS
        BEGIN
            EXECUTE IMMEDIATE p_sql;
        EXCEPTION
            WHEN OTHERS THEN
                -- -955: object already exists; -1408: column list already indexed.
                IF SQLCODE IN (-955, -1408) THEN NULL; ELSE RAISE; END IF;
        END;
    BEGIN
        ddl(q'{
            CREATE TABLE subjects (
                id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name       VARCHAR2(255) NOT NULL UNIQUE,
                deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK (deleted IN (0, 1)),
                created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
        }');

        ddl(q'{
            CREATE TABLE schema_contents (
                id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                schema_type     VARCHAR2(16) DEFAULT 'AVRO' NOT NULL,
                schema_text     CLOB NOT NULL,
                canonical_form  CLOB,
                fingerprint     VARCHAR2(128),
                raw_fingerprint VARCHAR2(128) NOT NULL,
                created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
        }');

        ddl(q'{
            CREATE TABLE schema_versions (
                id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                subject_id NUMBER(19) NOT NULL REFERENCES subjects(id),
                version    NUMBER(10) NOT NULL CHECK (version > 0),
                content_id NUMBER(19) NOT NULL REFERENCES schema_contents(id),
                deleted    NUMBER(1) DEFAULT 0 NOT NULL CHECK (deleted IN (0, 1)),
                created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT uq_schema_versions_subj_ver UNIQUE (subject_id, version)
            )
        }');

        ddl(q'{
            CREATE TABLE schema_references (
                id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content_id NUMBER(19) NOT NULL REFERENCES schema_contents(id),
                name       VARCHAR2(512) NOT NULL,
                subject    VARCHAR2(255) NOT NULL,
                version    NUMBER(10) NOT NULL
            )
        }');

        ddl(q'{
            CREATE TABLE config (
                id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                subject             VARCHAR2(255) UNIQUE,
                compatibility_level VARCHAR2(32),
                normalize           NUMBER(1) CHECK (normalize IN (0, 1)),
                registry_mode       VARCHAR2(32),
                updated_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
        }');

        -- Indexes (UNIQUE/PK constraints above already index name, (subject_id,
        -- version) and the primary keys, so those are not repeated here).
        ddl(q'{CREATE INDEX idx_schema_versions_content_id ON schema_versions(content_id)}');
        ddl(q'{CREATE INDEX idx_schema_contents_fingerprint ON schema_contents(fingerprint)}');
        ddl(q'{CREATE UNIQUE INDEX idx_schema_contents_raw_fingerprint ON schema_contents(raw_fingerprint)}');
        ddl(q'{CREATE INDEX idx_subjects_active ON subjects(deleted, name)}');
        ddl(q'{CREATE INDEX idx_schema_references_content_id ON schema_references(content_id)}');

        -- Enforce at most one global config row (subject IS NULL). Oracle UNIQUE
        -- allows many NULLs, so a function-based unique index maps every global
        -- row to the same key while leaving per-subject rows unindexed (NULL).
        ddl(q'{CREATE UNIQUE INDEX idx_config_global ON config (CASE WHEN subject IS NULL THEN 1 END)}');
    END;

    -- Global config row (subject = NULL means global). Run dynamically: the
    -- `config` table is created at run time by the block above, so a static
    -- INSERT would fail to compile (the table does not exist at compile time).
    -- Idempotent: the NOT EXISTS guard skips it when a global row is present, and
    -- ORA-00001 (lost race against a concurrent migrator, caught by the global
    -- unique index) is swallowed so concurrent boots both succeed.
    BEGIN
        EXECUTE IMMEDIATE q'{
            INSERT INTO config (subject, compatibility_level, registry_mode)
            SELECT NULL, 'BACKWARD', 'READWRITE' FROM dual
            WHERE NOT EXISTS (SELECT 1 FROM config WHERE subject IS NULL)
        }';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -1 THEN RAISE; END IF;
    END;

    COMMIT;
END;
